apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: account
  name: account
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: account
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: account
    spec:
      containers:
        - env:
            - name: APP_PORT
            - name: DB_HOST
            - name: DB_NAME
            - name: DB_PASSWORD
            - name: DB_PORT
            - name: DB_USERNAME
            - name: ENCRYPT_SECRET_KEY
            - name: JWT_SECRET_KEY
          image: aline-account-ry
          name: account
          ports:
            - containerPort: 8072
          resources: {}
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: account
  name: account
spec:
  ports:
    - name: "8072"
      port: 8072
      targetPort: 8072
  selector:
    io.kompose.service: account
status:
  loadBalancer: {}