apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: bank
  name: bank
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bank
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: bank
    spec:
      containers:
        - env:
            - name: APP_PORT
              value: "8083"
            - name: DB_HOST
              value: "cirrus-db.ctcaruquqjav.us-east-1.rds.amazonaws.com"
            - name: DB_NAME
              value: "alinedb"
            - name: DB_PASSWORD
              value: cirrusdb
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: "cirrusdb"
            - name: ENCRYPT_SECRET_KEY
              value: "thisisagreatsecretkey!!!"
            - name: JWT_SECRET_KEY
              value: "WmZq4t7w!z%C&F)J@NcRfUjXn2r5u8x/"
          image: 744758641322.dkr.ecr.us-east-1.amazonaws.com/aline-bank-ry
          name: bank
          ports:
            - containerPort: 8083
          resources: {}
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: bank
  name: bank
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8083
  selector:
    io.kompose.service: bank
status:
  loadBalancer: {}
