apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: underwriter
  name: underwriter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: underwriter
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: underwriter
    spec:
      containers:
        - env:
            - name: APP_PORT
            - name: DB_HOST
            - name: DB_NAME
            - name: DB_PASSWORD
            - name: DB_PORT
            - name: DB_USERNAME
            - name: ENCRYPT_SECRET_KEY
            - name: JWT_SECRET_KEY
          image: aline-underwriter-ry
          name: underwriter
          ports:
            - containerPort: 8071
          resources: {}
      restartPolicy: Always
status: {}
