---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: eks
  namespace: development
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::744758641322:role/validate-csi-setup-policy

# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: ry-aline-environment-variables
# spec:
#   provider: aws
#   secretObjects:                
#     - secretName: ry-aline-environment-variables
#       type: Opaque
#       data:
#         #- objectName: <objectName> or <objectAlias> 
#         - objectName: DB_NAME
#           key: DB_NAME

#         - objectName: DB_PORT
#           key: DB_PORT

#         - objectName: ENCRYPT_SECRET_KEY
#           key: ENCRYPT_SECRET_KEY

#         - objectName: JWT_SECRET_KEY
#           key: JWT_SECRET_KEY

#         - objectName: USER_M
#           key: USER_M

#         - objectName: UNDERWRITER_M
#           key: UNDERWRITER_M

#         - objectName: ACCOUNT_M
#           key: ACCOUNT_M

#         - objectName: BANK_M
#           key: BANK_M

#         - objectName: TRANSACTION_M
#           key: TRANSACTION_M

#         - objectName: GATEWAY_M
#           key: GATEWAY_M
          
#         - objectName: RDS_USERNAME
#           key: RDS_USERNAME

#         - objectName: RDS_PASSWORD
#           key: RDS_PASSWORD

#         - objectName: RDS_HOST
#           key: RDS_HOST

#         - objectName: ECR_URL
#           key: ECR_URL

#         - objectName: LOADBALANCER
#           key: LOADBALANCER

#         - objectName: LOADBALANCER_DNS
#           key: LOADBALANCER_DNS
  # parameters:
  #   objects: |
  #       - objectName: "RY-aline-environment-variables"
  #         objectType: "secretsmanager"
  #         jmesPath:
  #               - path: "DB_NAME"
  #                 objectAlias: "DB_NAME"

  #               - path: "DB_PORT"
  #                 objectAlias: "DB_PORT"

  #               - path: "ENCRYPT_SECRET_KEY"
  #                 objectAlias: "ENCRYPT_SECRET_KEY"

  #               - path: "JWT_SECRET_KEY"
  #                 objectAlias: "JWT_SECRET_KEY"

  #               - path: "USER_M"
  #                 objectAlias: "USER_M"

  #               - path: "UNDERWRITER_M"
  #                 objectAlias: "UNDERWRITER_M"

  #               - path: "ACCOUNT_M"
  #                 objectAlias: "ACCOUNT_M"

  #               - path: "BANK_M"
  #                 objectAlias: "BANK_M"

  #               - path: "TRANSACTION_M"
  #                 objectAlias: "TRANSACTION_M"

  #               - path: "GATEWAY_M"
  #                 objectAlias: "GATEWAY_M"

  #               - path: "RDS_USERNAME"
  #                 objectAlias: "RDS_USERNAME"

  #               - path: "RDS_PASSWORD"
  #                 objectAlias: "RDS_PASSWORD"

  #               - path: "RDS_HOST"
  #                 objectAlias: "RDS_HOST"

  #               - path: "ECR_URL"
  #                 objectAlias: "ECR_URL"

  #               - path: "LOADBALANCER"
  #                 objectAlias: "LOADBALANCER"

  #               - path: "LOADBALANCER_DNS"
  #                 objectAlias: "LOADBALANCER_DNS"
  
  # secretObjects:                
  #   - secretName: ry-aline-environment-variables
  #     type: Opaque
  #     data:
  #       #- objectName: <objectName> or <objectAlias> 
  #       - objectName: DB_NAME
  #         key: DB_NAME

  #       - objectName: DB_PORT
  #         key: DB_PORT

  #       - objectName: ENCRYPT_SECRET_KEY
  #         key: ENCRYPT_SECRET_KEY

  #       - objectName: JWT_SECRET_KEY
  #         key: JWT_SECRET_KEY

  #       - objectName: USER_M
  #         key: USER_M

  #       - objectName: UNDERWRITER_M
  #         key: UNDERWRITER_M

  #       - objectName: ACCOUNT_M
  #         key: ACCOUNT_M

  #       - objectName: BANK_M
  #         key: BANK_M

  #       - objectName: TRANSACTION_M
  #         key: TRANSACTION_M

  #       - objectName: GATEWAY_M
  #         key: GATEWAY_M
          
  #       - objectName: RDS_USERNAME
  #         key: RDS_USERNAME

  #       - objectName: RDS_PASSWORD
  #         key: RDS_PASSWORD

  #       - objectName: RDS_HOST
  #         key: RDS_HOST

  #       - objectName: ECR_URL
  #         key: ECR_URL

  #       - objectName: LOADBALANCER
  #         key: LOADBALANCER

  #       - objectName: LOADBALANCER_DNS
  #         key: LOADBALANCER_DNS
